project:
  type: website
  output-dir: docs

website:
  title: "Gabriel John Barrios"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - url: /files/CV_BarriosG (Edit).pdf
        text: CV
      - url: /files/Resume_BarriosG (Edit).pdf
        text: Resume

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



